# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robopresso_main_simulator_4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import bat_start
import bat_start_files


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(895, 420)
        font = QtGui.QFont()
        font.setFamily("911 Porscha")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: #000000;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_ONE_EXECUTION = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ONE_EXECUTION.setGeometry(QtCore.QRect(130, 170, 131, 121))
        font = QtGui.QFont()
        font.setFamily("A004견출새내기")
        font.setPointSize(10)
        self.pushButton_ONE_EXECUTION.setFont(font)
        self.pushButton_ONE_EXECUTION.setStyleSheet("QPushButton{\n"
                                                    "background-color: #00aafff;\n"
                                                    "color: #ffffff;\n"
                                                    "border: 1px;\n"
                                                    "border-radius: 10px;\n"
                                                    "}\n"
                                                    "QPushButton{\n"
                                                    "background-color: #00aaff;\n"
                                                    "border: 1px;\n"
                                                    "}")
        self.pushButton_ONE_EXECUTION.setObjectName("pushButton_ONE_EXECUTION")
        self.pushButton_TWO_EXECUTION = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_TWO_EXECUTION.setGeometry(QtCore.QRect(380, 170, 131, 121))
        font = QtGui.QFont()
        font.setFamily("A004견출새내기")
        font.setPointSize(10)
        self.pushButton_TWO_EXECUTION.setFont(font)
        self.pushButton_TWO_EXECUTION.setStyleSheet("QPushButton{\n"
                                                    "background-color: #00aafff;\n"
                                                    "color: #ffffff;\n"
                                                    "border: 1px;\n"
                                                    "border-radius: 10px;\n"
                                                    "}\n"
                                                    "QPushButton{\n"
                                                    "background-color: #00aaff;\n"
                                                    "border: 1px;\n"
                                                    "}")
        self.pushButton_TWO_EXECUTION.setObjectName("pushButton_TWO_EXECUTION")
        self.pushButton_ONE_HUNDERD_EXECUTION = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ONE_HUNDERD_EXECUTION.setGeometry(QtCore.QRect(620, 170, 131, 121))
        font = QtGui.QFont()
        font.setFamily("A004견출새내기")
        font.setPointSize(10)
        self.pushButton_ONE_HUNDERD_EXECUTION.setFont(font)
        self.pushButton_ONE_HUNDERD_EXECUTION.setStyleSheet("QPushButton{\n"
                                                            "background-color: #00aafff;\n"
                                                            "color: #ffffff;\n"
                                                            "border: 1px;\n"
                                                            "border-radius: 10px;\n"
                                                            "}\n"
                                                            "QPushButton{\n"
                                                            "background-color: #00aaff;\n"
                                                            "border: 1px;\n"
                                                            "}")
        self.pushButton_ONE_HUNDERD_EXECUTION.setObjectName("pushButton_ONE_HUNDERD_EXECUTION")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 40, 671, 51))
        font = QtGui.QFont()
        font.setFamily("A004견출새내기")
        font.setPointSize(28)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #ffff00;")
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 895, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_ONE_EXECUTION.clicked.connect(MainWindow.ONE_EXECUTION)
        self.pushButton_TWO_EXECUTION.clicked.connect(MainWindow.TWO_EXECUTION)
        self.pushButton_ONE_HUNDERD_EXECUTION.clicked.connect(MainWindow.ONE_HUNDRED_EXECUTION)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def ONE_EXECUTION(self):
        executeFir_BUTTON_ONE_EXECUTION = bat_start_files.bat_start_files.executeFir_BUTTON_ONE_EXECUTION
        bat_start.run_ONE_EXECUTION(executeFir_BUTTON_ONE_EXECUTION)

    def TWO_EXECUTION(self):
        executeFir_BUTTON_TWO_EXECUTION = bat_start_files.bat_start_files.executeFir_BUTTON_TWO_EXECUTION
        bat_start.run_TWO_EXECUTION(executeFir_BUTTON_TWO_EXECUTION)

    def ONE_HUNDRED_EXECUTION(self):
        executeFir_BUTTON_ONE_HUNDRED_EXECUTION = bat_start_files.bat_start_files.executeFir_BUTTON_ONE_HUNDED_EXECUTION
        bat_start.run_ONE_HUNDRED_EXECUTION(executeFir_BUTTON_ONE_HUNDRED_EXECUTION)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_ONE_EXECUTION.setText(_translate("MainWindow", "ONE\n"
                                                                       "\n"
                                                                       "EXECUTION"))
        self.pushButton_TWO_EXECUTION.setText(_translate("MainWindow", "TWO\n"
                                                                       "\n"
                                                                       "EXECUTION"))
        self.pushButton_ONE_HUNDERD_EXECUTION.setText(_translate("MainWindow", "ONE_HUNDRED\n"
                                                                               "\n"
                                                                               "EXECUTION"))
        self.label_4.setText(_translate("MainWindow", "ROBOPRESSO_SIMULATION_BUTTON"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
